language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - "10"
  - "11"
  - "8"
script:
  - yarn test:prod
  - yarn build
after_success:
  - yarn report-coverage
  - yarn deploy-docs
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
